### ISSUE TITLE
notebook-shim 0.2.0 is not on Pypi

### ISSUE THREAD

**Issue by martinRenou** [jupyter/notebook_shim#19]
It looks like `notebook-shim` 0.2.0 has not been published on Pypi:

https://pypi.org/project/notebook-shim/#history

**Comment by dlqqq** [comment]
Looks like it was published today; can we close this?

**Comment by jtpio** [comment]
Yes closing as it's now released: 

- https://github.com/jupyter/notebook_shim/releases/tag/v0.2.0
- https://pypi.org/project/notebook-shim/0.2.0/
