### ISSUE TITLE
v0.2.0 does not load all notebook extensions

### ISSUE THREAD

**Issue by st-bender** [jupyter/notebook_shim#22]
Hi,
It looks like updating `notebook-shim` from v0.1.0 to v0.2.0 breaks some notebook extensions, or does not load them. In particular `vim_binding` does not work anymore when using `jupyter nbclassic`.
Downgrading to v0.1.0 fixes the issue. Unfortunately no log or something to find out where it fails.
Cheers.

**Comment by ahyang98** [comment]
![image](https://user-images.githubusercontent.com/45085520/198969157-8d0cebfb-68f5-4e58-b5c1-592d92a36e57.png)
no notebook_shim.json in the package

**Comment by dleen** [comment]
I'm having the same issue. I've tracked the problem down to the commit to move to the hatch build backend: https://github.com/jupyter/notebook_shim/commit/fba73f4f9e440621b33eb1f3bc8f3609a70840ad

I wonder if something is depending on `setup.py` in order to load something or get some info.
